dailypulse/urls.py
from django.urls import path
from .views import DailypulseList, DailypulseDetail



urlpatterns = [
    path("", DailypulseList.as_view(), name="dailypulse_list"),
    path("<int:pk>/", DailypulseDetail.as_view(), name="dailypulse_detail")

]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework_simplejwt import views as jwt_views
from .views import MyTokenObtainPairView
from django.views.generic.base import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/v1/dailypulse/", include("dailypulse.urls")),
    path("api/v1/dailypulse/", include("dailypulse.urls_readinglist")),
    path("api/v1/dailypulse/", include("dailypulse.urls_comment")),
    path("api/v1/dailypulse/", include("dailypulse.urls_news")),
    path("api/v1/dailypulse/", include("dailypulse.urls_api")),
    path("api-auth/", include("rest_framework.urls")),
    path(
        "api/token/",
        MyTokenObtainPairView.as_view(),
        name="token_obtain_pair",
    ),
    path(
        "api/token/refresh/",
        jwt_views.TokenRefreshView.as_view(),
        name="token_refresh",
    ),
    path("dailypulse/", include("dailypulse.urls_front")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="about.html"), name="about"),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

dailypulse/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from datetime import date


class Dailypulse(models.Model):

    name = models.CharField(max_length=256)
    rating = models.IntegerField(default=0, blank=True)
    reviewer = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, null=True, blank=True
    )
    description = models.TextField(default="", null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('dailypulse_detail', args=[str(self.id)])


# reading later foreign key user
class Reading_later(models.Model):

    title = models.CharField(max_length=256)
    url = models.CharField(max_length=256)
    id = models.AutoField(primary_key=True)
    source = models.TextField(default="", null=True, blank=True)
    author = models.TextField(default="", null=True, blank=True)
    url_image = models.TextField(default="",null=True, blank=True)
    published_date = models.DateField(default='1996-07-30')
    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, null=True, blank=True
    )
    description = models.TextField(default="", null=True, blank=True)
    content = models.TextField(default="", null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('Reading_later', args=[str(self.id)])


# news with comment
class News(models.Model):
    # new_id created by default as primary key
    user = models.ForeignKey( get_user_model(), on_delete=models.CASCADE, null=True, blank=False)
    source = models.TextField(default="", null=True, blank=True)
    author = models.TextField(default="", null=True, blank=True)
    title = models.TextField(default="", null=True, blank=True)
    description = models.TextField(default="", null=True, blank=True)
    url = models.TextField(default="",null=True, blank=True)
    url_image = models.TextField(default="",null=True, blank=True )
    published_date = models.DateField(default='1996-07-30')
    content = models.TextField(default="", null=True, blank=True)
    def __str__(self):
        return self.title


# comments foreign key id news post foreign key user
class Comment(models.Model):
    # comment_id by default when django creating the model and its a primary key
    user = models.ForeignKey( get_user_model(), on_delete=models.CASCADE, null=True, blank=False)
    news = models.ForeignKey(News,on_delete=models.CASCADE, null=True, blank=True)
    newsTitle = models.TextField(default="", null=True, blank=True)
    userName = models.TextField(default="", null=True, blank=True)
    description = models.TextField(default="", null=True, blank=True)

    def __str__(self):
        return self.description

dailypulse/views.py
from rest_framework.generics import (
    ListCreateAPIView,
    RetrieveUpdateDestroyAPIView,
    ListAPIView,
    RetrieveDestroyAPIView,
    RetrieveUpdateAPIView

)
from .models import Dailypulse
from .permissions import IsOwnerOrReadOnly
from .serializers import DailypulseSerializer



class DailypulseList(ListCreateAPIView):
    queryset = Dailypulse.objects.all()
    serializer_class = DailypulseSerializer


class DailypulseDetail(RetrieveUpdateDestroyAPIView):
    permission_classes = (IsOwnerOrReadOnly,)
    queryset = Dailypulse.objects.all()
    serializer_class = DailypulseSerializer


# create reading list : body attributes  all exepet id
# delete reading list : requeiring id in url
# get reading list : requiring user id in url

# create comment : body attributes all
# delete comment : comment id url
# get comment : requeering user id and news id in url
# get comments : requeering news id in url
# update comment : comment id url ,body description

# create News : body attributes all
# get news : requering user id in url
# delete news : requeiring news id

# API ROUTES :
# route to get data require a category(q)
# route to get arabic news require a category(q)
# weather route link 'http://api.openweathermap.org/data/2.5/weather?q=LOCATION&appid=f22892654725839a44ff6db985f0b151' require the user ocation in url


# get USER info : user id url
# update USER : user id url , body attributes all

templates/dailypulse/dailypulse_create.html
{% extends 'base.html' %}

{% block content %}


  <div
    class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
    <form class="space-y-6" method="POST">
      {% csrf_token %}
      <h5 class="text-xl font-medium text-gray-900 dark:text-white">Create a Thing</h5>
      <div>
        <label for="id_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Thing Name</label>
        <input type="text" name="name" id="id_name"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               placeholder="e.g. celery" required>

      </div>
      <div>
        <label for="id_rating" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Thing Rating</label>
        <input type="number" name="rating" id="id_rating"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               value="0" min="0" max="5" required>
      </div>
      <div>
        <label for="id_reviewer" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Reviewer</label>
        <select name="reviewer" id="id_reviewer">
          {% for value, choice in form.fields.reviewer.choices %}
            <option value="{{ value }}">{{  choice }}</option>
          {% endfor %}
        </select>
      </div>


      <button type="submit"
              class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        Create
      </button>

    </form>
  </div>

{% endblock content %}

templates/dailypulse/dailypulse_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Thing</h1>
<form method="POST">
  {% csrf_token %}
  <p>Do you really want to delete "{{ dailypulse.name }}"?</p>
  <input type="submit" value="OK" />
</form>
{% endblock content %}

templates/dailypulse/dailypulse_detail.html
{% extends 'base.html' %} {% block content %}

<div
  class="space-y-8 p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700"
>
  <div class="flex">
    <h5
      class="flex-auto mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"
    >
      {{ dailypulse.name }}
    </h5>

    <a href="{% url 'dailypulse_update' dailypulse.pk %}">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        fill="currentColor"
        class="w-6 h-6 text-blue-600"
      >
        <path
          d="M21.731 2.269a2.625 2.625 0 00-3.712 0l-1.157 1.157 3.712 3.712 1.157-1.157a2.625 2.625 0 000-3.712zM19.513 8.199l-3.712-3.712-8.4 8.4a5.25 5.25 0 00-1.32 2.214l-.8 2.685a.75.75 0 00.933.933l2.685-.8a5.25 5.25 0 002.214-1.32l8.4-8.4z"
        />
        <path
          d="M5.25 5.25a3 3 0 00-3 3v10.5a3 3 0 003 3h10.5a3 3 0 003-3V13.5a.75.75 0 00-1.5 0v5.25a1.5 1.5 0 01-1.5 1.5H5.25a1.5 1.5 0 01-1.5-1.5V8.25a1.5 1.5 0 011.5-1.5h5.25a.75.75 0 000-1.5H5.25z"
        />
      </svg>
    </a>

    <a href="{% url 'dailypulse_delete' dailypulse.pk %}">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        fill="currentColor"
        class="w-6 h-6 text-red-600"
      >
        <path
          fill-rule="evenodd"
          d="M16.5 4.478v.227a48.816 48.816 0 013.878.512.75.75 0 11-.256 1.478l-.209-.035-1.005 13.07a3 3 0 01-2.991 2.77H8.084a3 3 0 01-2.991-2.77L4.087 6.66l-.209.035a.75.75 0 01-.256-1.478A48.567 48.567 0 017.5 4.705v-.227c0-1.564 1.213-2.9 2.816-2.951a52.662 52.662 0 013.369 0c1.603.051 2.815 1.387 2.815 2.951zm-6.136-1.452a51.196 51.196 0 013.273 0C14.39 3.05 15 3.684 15 4.478v.113a49.488 49.488 0 00-6 0v-.113c0-.794.609-1.428 1.364-1.452zm-.355 5.945a.75.75 0 10-1.5.058l.347 9a.75.75 0 101.499-.058l-.346-9zm5.48.058a.75.75 0 10-1.498-.058l-.347 9a.75.75 0 001.5.058l.345-9z"
          clip-rule="evenodd"
        />
      </svg>
    </a>
  </div>

  <h5
    class="flex-auto mb-2 text-md font-bold tracking-tight text-gray-900 dark:text-white"
  >
    Reviewed by: {{ dailypulse.reviewer }}
  </h5>

  <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
    {{ dailypulse.description }}
  </p>

  <div class="flex items-center">
    {% for i in "12345" %}

    <svg
      aria-hidden="true"
      class="w-5 h-5 {% if i > dailypulse.rating|slugify %}text-grey-300{% else %}text-yellow-400{% endif %}"
      fill="currentColor"
      viewBox="0 0 20 20"
      xmlns="http://www.w3.org/2000/svg"
    >
      <title>First star</title>
      <path
        d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
      ></path>
    </svg>
    {% endfor %}
  </div>

  <a
    href="https://en.wikipedia.org/wiki/{{ dailypulse.name }}"
    class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
  >
    Read more
    <svg
      aria-hidden="true"
      class="w-4 h-4 ml-2 -mr-1"
      fill="currentColor"
      viewBox="0 0 20 20"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        fill-rule="evenodd"
        d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
        clip-rule="evenodd"
      ></path>
    </svg>
  </a>
</div>

{% endblock content %}

templates/dailypulse/dailypulse_list.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="space-y-8 p-8">
  <h1 class="text-4xl text-center">All the Things</h1>
  <div
    class="w-1/2 mx-auto text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg dark:bg-gray-700 dark:border-gray-600 dark:text-white"
  >
    {% for dailypulse in dailypulses %}
    <a
      href="{% url 'dailypulse_detail' dailypulse.pk %}"
      aria-current="true"
      class="block w-full px-4 py-4 text-white bg-blue-700 border-b border-gray-200 rounded-t-lg cursor-pointer dark:bg-gray-800 dark:border-gray-600"
    >
      {{ dailypulse.name }}
    </a>
    {% endfor %}
  </div>
</div>

{% endblock content %}

templates/dailypulse/dailypulse_update.html
{% extends 'base.html' %} {% block content %}
<div
  class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700"
>
  <form class="space-y-6" method="POST">
    {% csrf_token %} {{form.as_p}}
    <button
      type="submit"
      class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
    >
      Ubdate
    </button>
  </form>
</div>
{% endblock content %}